name: Moodle Plugin Release

on:
  release:
    types: [published]

jobs:
  call-learnweb-release-workflow:
    uses: learnweb/moodle-workflows-learnweb/.github/workflows/moodle-release.yml@main
    with:
      plugin-name: 'mod_moodleoverflow'
    secrets: inherit
