name: Moodle Plugin CI
on: [push, pull_request]

jobs:
  call-learnweb-ci-workflow:
    name: "Learnweb CI Workflow"
    uses: learnweb/moodle-workflows-learnweb/.github/workflows/moodle-ci.yml@main
    with:
      allow-mustache-lint-error: true
